CREATE TABLE Users ( 
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL, 
    Bio VARCHAR(100), 
    Email VARCHAR(100) UNIQUE NOT NULL, 
    Portfolio VARCHAR(255), 
    Picture_URL VARCHAR(255), 
    Residency_ID INT NOT NULL, 
    Socials VARCHAR(100) ); 

CREATE TABLE Residency ( 
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    Residency_Name VARCHAR(100) NOT NULL, 
    Year INT NOT NULL ); 

CREATE TABLE PersonResidency ( 
    PersonID INT NOT NULL, 
    ResidencyID INT NOT NULL, 
    FOREIGN KEY (PersonID) REFERENCES Users(ID), 
    FOREIGN KEY (ResidencyID) REFERENCES Residency(ID) )

CREATE TABLE Posts ( 
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    Author_ID INT NOT NULL, 
    Title VARCHAR(255) NOT NULL, 
    Description TEXT, Tag_ID INT, 
    Picture_URL VARCHAR(255), 
    Post_Date DATETIME NOT NULL, 
    Active BOOLEAN NOT NULL DEFAULT TRUE, 
    FOREIGN KEY (Author_ID) REFERENCES Users(ID) );

CREATE TABLE Tags ( 
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    Tag VARCHAR(50) NOT NULL );
